# Generated by Django 4.0.1 on 2022-01-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('API', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Auth', models.CharField(blank=True, max_length=100)),
                ('HTTP', models.BooleanField(default=False)),
                ('Cors', models.CharField(max_length=10)),
                ('Link', models.CharField(max_length=200)),
                ('Category', models.CharField(max_length=100)),
            ],
        ),
    ]
